### ISSUE TITLE
Throw exception

### ISSUE THREAD

**Issue by sw-tracker** [gmazzo/okhttp-client-mock#11]
Hi there,

I would like to throw an exception when `httpClient.newCall(request).execute()` runs as part of my unit tests. How can I do this with your mock?

Cheers,
Olga

**Comment by gmazzo** [comment]
You can archive that with the `Answer` pattern:
```kotlin
    rule(get) {
        respond { throw IllegalStateException("an IO error") }
    }
```

**Comment by sw-tracker** [comment]
and in java?

**Comment by gmazzo** [comment]
In java will be:
```java
interceptor.addRule()
        ...
        .answer(request -> throw new IllegalStateException("an IO error"))
```
