### ISSUE TITLE
Build failed due to repo.spring.io anonymous user restriction

### ISSUE THREAD

**Issue by naheedk-pwc** [gmazzo/okhttp-client-mock#7]
I am trying to build dapr framework, build is failing due to not above find    https://repo.spring.io/snapshot/com/github/gmazzo/okhttp-mock/ jar files.  It is available at https://repo.spring.io/libs-milestone/com/github/gmazzo/okhttp-mock/1.3.2/ , however not accessible as anonymous user is restricted.
Thanks
Naheed

**Comment by gmazzo** [comment]
Hello there, you should reach String's team support for this, as I'm not
publishing on their repo. My library is available at JCenter
https://bintray.com/gmazzo/maven/okhttp-client-mock/1.3.2

Regards!

**Comment by gmazzo** [comment]
Now, version `1.4.0` is available at MavenCentral
