### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by sw-tracker** [gmazzo/okhttp-client-mock#9]
Hi there,

What version can I use with java 8?

I keep getting this error:
`bad class file: /home/runner/.m2/repository/com/github/gmazzo/okhttp-mock/1.4.0/okhttp-mock-1.4.0.jar(okhttp3/mock/MockInterceptor.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.`

Thanks,
Olga

**Comment by gmazzo** [comment]
Fixed in https://github.com/gmazzo/okhttp-client-mock/pull/10

**Comment by sw-tracker** [comment]
Maven version? 1.4.0 doesn't seem to work.

**Comment by gmazzo** [comment]
Just released it as `1.4.1`
https://search.maven.org/artifact/com.github.gmazzo/okhttp-mock/1.4.1/jar
